apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.metadata.name }}
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
  template:
    metadata:
      name: {{ .Values.client.template.name }}
      labels:
        app: {{ .Values.client.name }}
    spec:
      containers:
        - name: {{ .Values.client.name }}
          image: {{ .Values.client.image }}