apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.metadata.name }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
  template:
    metadata:
      name: {{ .Values.server.template.name }}
      labels:
        app: {{ .Values.server.name }}
    spec:
      containers:
        - name: {{ .Values.server.name }}
          image: {{ .Values.server.image }}